# -*- coding: utf-8 -*-
"""volleyball_detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MKPJ5bkjfBbDWeD-k4OmJV55H9OxAvxa

# Mount the drive
"""

from google.colab import drive
drive.mount('/content/gdrive')

!pwd

# Commented out IPython magic to ensure Python compatibility.
# %cd "/content/gdrive/MyDrive/Volleyball_detection"

"""# Clone the DarkNet"""

!git clone "https://github.com/AlexeyAB/darknet.git" "/content/gdrive/MyDrive/Volleyball_detection/darknet"

"""# Change Makefile to enabled GPU OPENCV and CUDNN"""

# Commented out IPython magic to ensure Python compatibility.
# %cd "/content/gdrive/MyDrive/Volleyball_detection/darknet"
!sed -i 's/OPENCV=0/OPENCV=1/' Makefile
!sed -i 's/GPU=0/GPU=1/' Makefile
!sed -i 's/CUDNN=0/CUDNN=1/' Makefile
!make

"""### Copy and Customize the configuration files of darknet according to our data like No.of classes , No.of filters, max_batches and steps"""

!cp cfg/yolov3.cfg cfg/volleyball.cfg

!pwd

"""### Create custom_weight directory and download a darknet53.conv.74 file in it"""

# Commented out IPython magic to ensure Python compatibility.
!mkdir custom_weight
# %cd "/content/gdrive/MyDrive/Volleyball_detection/custom_weight"
!wget https://pjreddie.com/media/files/darknet53.conv.74
!pwd
# %cd ..

"""# Unzip the data"""

!unzip "/content/gdrive/MyDrive/Volleyball_detection/train.zip" -d "/content/gdrive/MyDrive/Volleyball_detection"

"""### Upload classes.txt and classes.names file in train directory which includes classes of datasets

# Create train.txt, test.txt and labelled_data.data
"""

!python train/creating-files-data-and-name.py

!python train/creating-train-and-test-txt-files.py

"""### Create backup directory to save all the trained weights"""

# Commented out IPython magic to ensure Python compatibility.
!pwd
# %cd "/content/gdrive/MyDrive/Volleyball_detection"
!mkdir "backup"

"""### Train the Model"""

!darknet/darknet

!darknet/darknet detector train train/labelled_data.data darknet/cfg/volleyball.cfg custom_weight/darknet53.conv.74 -dont_show



